
import { Button } from "@/components/ui/button";
import { Mic, Upload, Play, Wand2 } from "lucide-react";
import { motion } from "framer-motion";

const VoiceChangerHero = () => {
    return (
        <section className="relative pt-32 pb-20 px-4 overflow-hidden bg-gradient-to-b from-white to-gray-50/50">
            <div className="max-w-7xl mx-auto text-center space-y-8 relative z-10">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="space-y-6 max-w-4xl mx-auto"
                >
                    <h1 className="text-5xl md:text-7xl font-bold tracking-tight text-gray-900 leading-[1.1]">
                        Transform your voice into another while preserving{" "}
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-gray-900 to-gray-600">
                            emotion, delivery, and nuance
                        </span>
                        .
                    </h1>

                    <p className="text-xl md:text-2xl text-gray-600 max-w-2xl mx-auto font-light leading-relaxed">
                        Full control over your performance. Capture every whisper, laugh, and accent
                        with our advanced medical-grade voice AI.
                    </p>

                    <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
                        <Button size="lg" className="rounded-full px-8 h-12 text-base font-medium bg-black hover:bg-gray-800 text-white min-w-[160px]">
                            Try For Free
                        </Button>
                        <Button size="lg" variant="outline" className="rounded-full px-8 h-12 text-base font-medium border-gray-200 hover:bg-gray-50 text-gray-900 min-w-[160px]">
                            View Pricing
                        </Button>
                    </div>
                </motion.div>

                {/* Interactive Demo Card */}
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, delay: 0.2 }}
                    className="mt-20 max-w-3xl mx-auto bg-white rounded-3xl shadow-xl border border-gray-100 p-2 overflow-hidden"
                >
                    <div className="bg-gray-50/50 rounded-2xl p-8 md:p-12 space-y-8">
                        <div className="text-center space-y-2">
                            <h3 className="text-2xl font-semibold text-gray-900">What is an AI Voice Changer?</h3>
                            <p className="text-gray-500">Enable mic access, record yourself reading some prompts and generate the sample in different voices.</p>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <button className="flex flex-col items-center justify-center gap-4 p-8 bg-white border-2 border-dashed border-gray-200 rounded-2xl hover:border-blue-500 hover:bg-blue-50/10 transition-all group">
                                <div className="w-16 h-16 rounded-full bg-blue-50 flex items-center justify-center group-hover:scale-110 transition-transform">
                                    <Upload className="w-8 h-8 text-blue-600" />
                                </div>
                                <span className="font-medium text-gray-600">Upload audio</span>
                            </button>

                            <button className="flex flex-col items-center justify-center gap-4 p-8 bg-white border-2 border-gray-100 rounded-2xl hover:border-blue-500 hover:bg-blue-50/10 transition-all group shadow-sm">
                                <div className="w-16 h-16 rounded-full bg-red-50 flex items-center justify-center group-hover:scale-110 transition-transform relative">
                                    <div className="absolute inset-0 bg-red-400/20 rounded-full animate-ping" />
                                    <Mic className="w-8 h-8 text-red-500 relative z-10" />
                                </div>
                                <span className="font-medium text-gray-900">Start recording</span>
                            </button>
                        </div>

                        <div className="flex items-center justify-center gap-8 pt-4 opacity-50 pointer-events-none">
                            <div className="flex items-center gap-2 text-sm text-gray-400">
                                <Wand2 className="w-4 h-4" />
                                Generated by ElevenLabs
                            </div>
                        </div>
                    </div>
                </motion.div>
            </div>

            {/* Decorative background elements */}
            <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-gray-200 to-transparent" />
            <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] pointer-events-none" />
        </section>
    );
};

export default VoiceChangerHero;
