import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Minus } from 'lucide-react';

const musicFaqs = [
    {
        question: "How does the Eleven Music generator work?",
        answer: "Our music generator uses advanced AI models trained on a vast library of music. It understands melody, harmony, rhythm, and instrumentation, allowing it to compose unique tracks based on your text prompts."
    },
    {
        question: "Can I generate music with vocals?",
        answer: "Yes, you can describe the type of vocals you'd like in your prompt, or use the 'Lyrics' feature to provide specific words for the AI to sing or rap."
    },
    {
        question: "Is the music royalty-free for commercial use?",
        answer: "Music generated by users on a paid plan (Starter or higher) includes a commercial license. This means you can use the tracks in your monetized YouTube videos, games, ads, and other commercial projects."
    },
    {
        question: "What audio formats are available for download?",
        answer: "You can download your generated tracks in high-quality WAV (44.1kHz) or MP3 (320kbps). Paid users also have access to stems (vocals, drums, instruments) for more advanced editing."
    },
    {
        question: "How long can the generated tracks be?",
        answer: "Currently, you can generate tracks ranging from a few seconds for stings and loops up to 3 minutes for full compositions."
    }
];

const MusicFAQ = () => {
    const [activeIndex, setActiveIndex] = useState<number | null>(0);

    return (
        <section className="py-24 bg-white font-sans">
            <div className="container mx-auto px-4 lg:px-8">
                <div className="max-w-3xl mx-auto">
                    <div className="text-center mb-16">
                        <h2 className="text-4xl font-bold text-[#1D1D1B] mb-4">Frequently Asked Questions</h2>
                        <p className="text-[#1D1D1B]/60 font-medium">Everything you need to know about AI-generated music.</p>
                    </div>

                    <div className="space-y-4">
                        {musicFaqs.map((faq, i) => (
                            <div key={i} className="border-b border-black/5">
                                <button
                                    onClick={() => setActiveIndex(activeIndex === i ? null : i)}
                                    className="w-full py-6 flex items-center justify-between text-left group"
                                >
                                    <span className="text-lg font-bold text-[#1D1D1B] group-hover:text-[#1D1D1B]/80 transition-colors">
                                        {faq.question}
                                    </span>
                                    <div className="w-6 h-6 flex items-center justify-center rounded-full bg-black/5">
                                        {activeIndex === i ? (
                                            <Minus className="w-4 h-4" />
                                        ) : (
                                            <Plus className="w-4 h-4" />
                                        )}
                                    </div>
                                </button>
                                <AnimatePresence>
                                    {activeIndex === i && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: "auto", opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.3, ease: "easeInOut" }}
                                            className="overflow-hidden"
                                        >
                                            <p className="pb-8 text-[#1D1D1B]/60 font-medium leading-relaxed">
                                                {faq.answer}
                                            </p>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>
    );
};

export default MusicFAQ;
